# Generated by Django 3.2 on 2022-01-11 23:57

from django.db import migrations, models
import django.db.models.deletion
from producto.models import Categoria,Proveedor,Articulo


class Migration(migrations.Migration):
    
    def insert_data(apps, schema_editor):
        ## Categorias
        anillos = Categoria.objects.create(nombre="ANILLOS")
        aretes = Categoria.objects.create(nombre="ARETES")
        cadenas = Categoria.objects.create(nombre="CADENAS")
        joyeros = Categoria.objects.create(nombre="JOYEROS")
        piercings = Categoria.objects.create(nombre="PIERCINGS_FALSOS")
        pulseras = Categoria.objects.create(nombre="PULSERAS")
        relojes = Categoria.objects.create(nombre="RELOJES")
        
        
        ## Proveedores
        proveedor = Proveedor.objects.create(nombre="Joyeria S.A.")
        
        
        ## Articulos
        
        # anillos
        Articulo.objects.create(nombre="Chunky XL Rings", categoria=anillos, promocion=12, precio=15, proveedor=proveedor,image_url="https://s.yimg.com/ny/api/res/1.2/4EYp6MiQq4OhgE2EHQ1B9A--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MA--/https://media.zenfs.com/en/who_what_wear_581/5de5124ea8aa14be956fb496a8c3895b")
        Articulo.objects.create(nombre="Classic Rings", categoria=anillos, precio=10, proveedor=proveedor,image_url="https://cdn.shopify.com/s/files/1/1961/2931/products/diamond-wedding-band-half-eternity-ring-yellow-gold-by-la-more-design-3.JPG?v=1525368961")
        Articulo.objects.create(nombre="Chunky Rings", categoria=anillos, precio=12, proveedor=proveedor, image_url="https://www.weddingforward.com/wp-content/uploads/2020/01/wedding-rings-for-women-wedding-bands-materialgood-1.jpg")
        Articulo.objects.create(nombre="Brown Ring Game", categoria=anillos, precio=4, proveedor=proveedor, image_url="https://hips.hearstapps.com/elleuk.cdnds.net/17/11/480x482/jenniekwondesigns2.png?resize=480:*")
        Articulo.objects.create(nombre="Pinky Rings Game", categoria=anillos, promocion=4, precio=6, proveedor=proveedor, image_url="https://cdn0.hitched.co.uk/article/2287/original/1280/jpg/97822-stacked-rings.jpeg")
        Articulo.objects.create(nombre="Perls Rings", categoria=anillos, precio=4, proveedor=proveedor, image_url="https://i.pinimg.com/474x/0d/9c/d1/0d9cd190d3aca5448f4a832707c6cc46.jpg")
        
        # aretes
        Articulo.objects.create(nombre="Happy Faces Earrings", categoria=aretes, precio=8, proveedor=proveedor, image_url="https://cdn.shopify.com/s/files/1/1090/1794/products/Chupi-Solid-Gold-Stud-Earrings-Edwardian-Bezel-Recycled-Diamond-1_700x700.jpg?v=1631520792")
        Articulo.objects.create(nombre="Girly Happy Faces Earrings", categoria=aretes, precio=10, proveedor=proveedor, image_url="https://www.orra.co.in/pub/media/catalog/product/o/p/ope16080-a.jpg")
        Articulo.objects.create(nombre="Clasic Earrings", categoria=aretes, precio=6, proveedor=proveedor, image_url="https://cdn11.bigcommerce.com/s-thiekn1go9/images/stencil/500x500/products/1005/1996/bezel-baby-diamond-earrings-.20tcw-14k-yellow-gold-web__33672.1596159556.jpg?c=2")
        Articulo.objects.create(nombre="Butterfly Earrings", categoria=aretes, precio=10, proveedor=proveedor, image_url="https://rohanjewellers.com.au/wp-content/uploads/2020/02/G6819-1024x1024.jpg")
        
        # cadenas
        Articulo.objects.create(nombre="Maxi Charms", categoria=cadenas, precio=15, proveedor=proveedor, image_url="https://cdn.notonthehighstreet.com/system/product_images/images/002/368/282/original_silver-or-gold-om-necklace.jpg")
        Articulo.objects.create(nombre="Flower Chain", categoria=cadenas, precio=15, proveedor=proveedor, image_url="https://ae01.alicdn.com/kf/Hc42295fa827f448480c157153e424956L/Dubai-India-Set-Jewelry-Necklace-pendant-Earring-22-K-23-K-24-K-Thai-Baht-Solid.jpg_Q90.jpg_.webp")
        Articulo.objects.create(nombre="Brilliant Charm", categoria=cadenas, precio=13, proveedor=proveedor, image_url="https://ae01.alicdn.com/kf/HTB1h83kGAOWBuNjSsppq6xPgpXad/Heart-muslim-allah-Classical-Necklaces-Earrings-Set-Solid-Gold-Filled-Brass-Wedding-Bride-s-Dowry-party.jpg_Q90.jpg_.webp")
        Articulo.objects.create(nombre="Sunflower Charm", categoria=cadenas, precio=15, proveedor=proveedor, image_url="https://cdn.shopify.com/s/files/1/0645/7107/files/solid-gold-fingerprint-handprint-footprint-pawprint-jewellery-hold-upon-heart_1600x.jpg?v=1633773925")
        Articulo.objects.create(nombre="Classic Charms", categoria=cadenas, precio=12, proveedor=proveedor, image_url="https://www.dhresource.com/0x0/f2/albu/g19/M00/B2/6F/rBVapmEXd2CAZyk_AA3vCTA3LKE407.jpg/22k-solid-fine-gold-18ct-thai-baht-g-f-necklace.jpg")
        Articulo.objects.create(nombre="Double", categoria=cadenas, precio=18, proveedor=proveedor, image_url="https://cdn.shopify.com/s/files/1/0604/4529/products/14KGoldGrowWithGraceDiamondNecklace_Front_800x900.jpg?v=1637127446")
        Articulo.objects.create(nombre="Guadalupe's Virgin Charm", categoria=cadenas, precio=13, proveedor=proveedor, image_url="https://cdn.shopify.com/s/files/1/0684/1595/products/solid_lockets_cropped_920x.jpg?v=1572682688")
        Articulo.objects.create(nombre="Religius Charm", categoria=cadenas, precio=40, proveedor=proveedor, image_url="https://cdn.shopify.com/s/files/1/0725/9895/products/Solid-Gold-Charm-Circle-Citrine-2_1024x1024.jpg?v=1635426202")
        
        # joyeros
        Articulo.objects.create(nombre="Medium Jewerly Box", categoria=joyeros, precio=30, proveedor=proveedor, image_url="https://m.media-amazon.com/images/I/81a9ZUhlmRL._AC_SX466_.jpg")
        
        # piercings
        Articulo.objects.create(nombre="Tripple Chunky Fake Piercing", categoria=piercings, precio=10, proveedor=proveedor, image_url="https://www.okamicorp.com/wp-content/uploads/2021/08/IMG_5557-scaled.jpg")
        Articulo.objects.create(nombre="Chainy Fake Piercing", categoria=piercings, precio=8, proveedor=proveedor, image_url="https://www.okamicorp.com/wp-content/uploads/2021/08/IMG_5558-scaled.jpg")
        Articulo.objects.create(nombre="Colorful Fake Piercing", categoria=piercings, precio=8, proveedor=proveedor, image_url="https://i.pinimg.com/originals/bb/f7/7a/bbf77ae3c2f4abd18b6f5082aac38c13.jpg")
        
        # pulseras
        Articulo.objects.create(nombre="Initial Bracelets", categoria=pulseras, promocion=12, precio=14, proveedor=proveedor, image_url="https://ae01.alicdn.com/kf/H0579e6a83e4e41ff84960ec85d0d1e33r/DIEZI-Bohemian-Rhinestone-Butterfly-Bracelets-Elegant-Cuff-Bangle-For-Women-Gold-Color-Chain-Bracelet-Sets-Vintage.jpg_Q90.jpg_.webp")
        Articulo.objects.create(nombre="Distance Couple Bracelets (Clear)", categoria=pulseras, precio=15, proveedor=proveedor, image_url="https://ae01.alicdn.com/kf/H5f4661d1d12e467bb8ef1fd466aad2f7N/ZMZY-Boho-Style-Stainless-Steel-Chain-Bracelets-For-Women-Cute-Crown-Bracelet-Beads-Bracelet-Femme-Girls.jpg")
        Articulo.objects.create(nombre="Distance Couple Bracelets", categoria=pulseras, precio=15, proveedor=proveedor, image_url="https://zoodmall.com/cdn-cgi/image/w=500,fit=contain,f=auto/https://ae01.alicdn.com/kf/Hbc2d04f8f56844639f5dcc478655184bS/5-Pcs-Set-Gold-Color-Open-Cuff-Bracelets-for-Women-Link-Chain-Bracelets-Bangles-Set-Fashion.jpg")
        Articulo.objects.create(nombre="Royalty Bracelets", categoria=pulseras, precio=18, proveedor=proveedor, image_url="https://cdn.shopify.com/s/files/1/0019/4776/2747/products/Charm-Jewelry-Set-4pcs-Charm-Cuban-Chain-Bracelets-Set-For-Women-Miami-Bohemia-Thick-Gold-Bracelets-Bangles-Fashion-2021-Touchy-Style-19.jpg?v=1630189293")
        Articulo.objects.create(nombre="Chunky Perls Bracelets", categoria=pulseras, promocion=15, precio=20, proveedor=proveedor, image_url="https://ae01.alicdn.com/kf/H89596b0b33a24db984bcba6e3d6f398fi/VKME-Bohemian-Multi-layer-Snake-Pendant-Anklets-Set-For-Women-Gold-Chain-Anklet-Foot-Ankle-Bracelet.jpg")
        Articulo.objects.create(nombre="Red Protected Bracelet", categoria=pulseras, precio=8, proveedor=proveedor, image_url="https://ae01.alicdn.com/kf/Hc07a34fde0b4434a81ce88942d7c9227x/ZMZY-Boho-Style-Stainless-Steel-Chain-Bracelets-For-Women-Cute-Crown-Bracelet-Beads-Bracelet-Femme-Girls.jpg_Q90.jpg_.webp")
        
        # relojes
        Articulo.objects.create(nombre="Silver Baby G", categoria=relojes, precio=20, proveedor=proveedor, image_url="https://qph.fs.quoracdn.net/main-qimg-72dacf81cc95c36171c0cfa9253370cd")
        Articulo.objects.create(nombre="Silver G Shock", categoria=relojes, precio=20, proveedor=proveedor, image_url="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/strap-1-1600699485.png?resize=640:*")
        Articulo.objects.create(nombre="Casio Rose Gold", categoria=relojes, precio=20, proveedor=proveedor, image_url="https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1621962564-watch-and-strap-under-1k-medium-diver-s-automatic-1621962558.jpg")
        Articulo.objects.create(nombre="Gold Baby G", categoria=relojes, precio=16, proveedor=proveedor, image_url="https://www.ticwatches.co.uk/images/g-shock-ga-2100-7aer-casioak-octagon-white-black-unisex-watch-p36780-56720_image.jpg")

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=1024)),
                ('promocion', models.DecimalField(decimal_places=2, max_digits=10,null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.categoria')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.proveedor')),
                ('stock',models.IntegerField(default=5))
            ],
        ),
        migrations.RunPython(insert_data),
    ]
