# Generated by Django 3.2 on 2022-01-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=5),
        ),
    ]
