# Generated by Django 3.2 on 2022-01-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User,Group
from authenticate.models import Profile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    def insert_data(apps,schema_editor):
        g_admin = Group.objects.create(name="admin")
        Group.objects.create(name="cliente")
        
        user:User = User()
        user.first_name = "admin"
        user.last_name = "apellido"
        user.email = "admin@example.com"
        user.username = "admin@example.com"
        user.set_password("Prueba_123")
        user.save()
        
        
        user.groups.add(g_admin)
        user.save()
        
        Profile.objects.create(user=user,telefono="0954125478",direccion="Enrique Segoviano")

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(insert_data)
    ]
